version: '3'
services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./quiz.db:/app/quiz.db
<<<<<<< HEAD
=======
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
>>>>>>> develop

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/web/uploads
<<<<<<< HEAD
=======
    depends_on:
      backend:
        condition: service_healthy
>>>>>>> develop
  